Repository kubewarden/kwctl, pull requests merged in 2022-12, with the labels that each got.

#386 fix: use system certificates
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#385 chore: update to latest policy-evaluator
  Cargo.lock
  Cargo.toml
  src/backend.rs
  src/bench.rs
  src/run.rs
Labels: kind/chore, area/dependencies

#391 Run autolabeler when a PR is edited
  .github/workflows/release-drafter.yml
Labels: kind/bug, area/ci
