Repository kubewarden/kwctl, pull requests merged in 2023-02, with the labels that each got.

#422 fix: scaffold should not generate the backgroundAudit field
  Cargo.lock
  src/scaffold.rs
Labels: kind/bug

#431 Context aware
  Cargo.lock
  Cargo.toml
  src/cli.rs
  src/inspect.rs
  src/main.rs
  src/policies.rs
  src/run.rs
  src/scaffold.rs
Labels: kind/enhancement

#434 chore: List AUR package in README.md
  README.md
Labels: kind/chore
