Repository kubewarden/kwctl, pull requests merged in 2023-06, with the labels that each got.

#509 chore(deps): update policy-evaluator
  Cargo.lock
  Cargo.toml
  src/inspect.rs
Labels: kind/chore, area/dependencies

#518 feat: support WASI policy
  Cargo.lock
  Cargo.toml
  src/annotate.rs
  src/backend.rs
  src/cli.rs
  src/run.rs
Labels: kind/enhancement

#526 fix: publish release drafter draft release.
  .github/release-drafter.yml
Labels: kind/bug, area/ci
