Repository kubewarden/kwctl, pull requests merged in 2023-01, with the labels that each got.

#396 Trigger Helm chart release.
  .github/workflows/release.yml
Labels: release/skip-changelog

#405 Fix release drafter autolabeler and exclude-labels.
  .github/release-drafter.yml
Labels: kind/bug, area/ci, release/skip-changelog

#407 Configure mdcat to use rustls.
  Cargo.lock
  Cargo.toml
Labels: kind/bug, area/ci

#410 fix: report the right version
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#408 Run continuous integration on every change.
  .github/workflows/build.yml
  .github/workflows/cargo-file-checks.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .github/workflows/source-code-checks.yml
  .github/workflows/tests.yml
Labels: kind/enhancement, area/ci

#411 fix airgap links
  Cargo.lock
  Cargo.toml
Labels: kind/bug
