Repository kubewarden/kwctl, pull requests merged in 2023-03, with the labels that each got.

#436 feat: Add `kwctl scaffold artifacthub` command, add `kwctl annotate --usage` flag
  Cargo.lock
  Cargo.toml
  src/annotate.rs
  src/cli.rs
  src/main.rs
  src/scaffold.rs
Labels: kind/enhancement

#446 fix: Serialize artifacthub-pkg.yml deterministically, bump to 1.6.0-rc2
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#449 feat: introduce record/replay of host capabilities
  Cargo.lock
  src/callback_handler/mod.rs
  src/callback_handler/proxy.rs
  src/cli.rs
  src/main.rs
  src/run.rs
Labels: kind/enhancement

#451 chore: fix cargo audit
  .cargo/audit.toml
Labels: kind/bug, kind/chore

#453 fix: allow execution of e2e tests when k8s is not available
  Cargo.lock
  Cargo.toml
  src/run.rs
Labels: kind/bug

#455 feat: --output flag to scaffold artifacthub command.
  src/cli.rs
  src/main.rs
Labels: kind/enhancement

#459 chore(deps): update mdcat to latest version
  Cargo.toml
  src/main.rs
Labels: kind/chore, area/dependencies

#460 fix: address small leftover
  src/info.rs
Labels: kind/bug

#462 fix: hide walrus warning message
  src/main.rs
Labels: kind/bug
