Repository kubewarden/kwctl, pull requests merged in 2024-04, with the labels that each got.

#764 fix(ci): cargo install ignores lockfile if --locked is not passed
  .github/workflows/ci.yml
Labels: kind/bug

#765 test: rewrite airgap tests as integration tests
  .github/workflows/ci.yml
  scripts/kubewarden-load-policies.sh
  scripts/kubewarden-save-policies.sh
  tests/airgap.rs
  tests/common/mod.rs
  tests/data/airgap/insecure.yml
  tests/secure_supply_chain_e2e.rs
Labels: area/ci, kind/tech-debt

#766 build(deps): remove unused dependencies
  Cargo.lock
  Cargo.toml
Labels: kind/chore, area/dependencies

#771 chore: bump version to 1.12.0-rc1
  Cargo.lock
  Cargo.toml
Labels: kind/chore

#773 fix: address changes done to Sigstore TUF repository
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  src/callback_handler/mod.rs
  src/callback_handler/proxy.rs
  src/cli.rs
  src/main.rs
  src/run.rs
  src/verify.rs
  tests/secure_supply_chain_e2e.rs
Labels: kind/bug
