Repository kubewarden/kwctl, pull requests merged in 2024-06, with the labels that each got.

#834 feat: scaffold KW policy from Kubernetes ValidatingAdmissionPolicy
  Cargo.lock
  Cargo.toml
  src/cli.rs
  src/main.rs
  src/scaffold.rs
  tests/data/vap/vap-binding.yml
  tests/data/vap/vap-with-variables.yml
  tests/data/vap/vap-without-variables.yml
  tests/e2e.rs
Labels: kind/feature

#837 fix: improve error handling in settings validation.
  src/main.rs
  src/run.rs
Labels: kind/bug

#838 chore: bump version to v1.14.0-rc1
  Cargo.lock
  Cargo.toml
Labels: kind/chore

#842 chore: bump version to v1.14.0-rc2
  Cargo.lock
  Cargo.toml
Labels: kind/chore

#843 chore: bump version to v1.14.0
  Cargo.lock
  Cargo.toml
Labels: kind/chore
