Repository kubewarden/kwctl, pull requests merged in 2024-09, with the labels that each got.

#905 chore: update cargo audit ignore list
  .cargo/audit.toml
Labels: area/dependencies

#912 chore: prepare for release v1.17.0-rc2
  Cargo.lock
  Cargo.toml
Labels: kind/chore

#930 chore(deps): bump policy-evaluator
  Cargo.lock
  Cargo.toml
Labels: kind/chore, area/dependencies
