Repository kubewarden/kwctl, pull requests merged in 2024-05, with the labels that each got.

#809 build(deps): bump policy-evaluator version to v0.17.2
  Cargo.lock
  Cargo.toml
Labels: area/dependencies

#810 build(deps): bump policy-evaluator version to v0.17.3
  Cargo.lock
  Cargo.toml
Labels: area/dependencies

#811 chore(deps): change GH action used by cargo-audit
  .github/workflows/security-audit-cron.yml
  .github/workflows/security-audit-reactive.yml
Labels: kind/chore, area/dependencies

#812 chore: prepare to release v1.13.0 rc1
  Cargo.lock
  Cargo.toml
Labels: kind/chore

#823 chore: add Kubewarden repository badges.
  README.md
Labels: kind/chore
