Repository kubewarden/kwctl, pull requests merged in 2024-03, with the labels that each got.

#737 chore: bump version to v1.11.0-rc2
  Cargo.lock
  Cargo.toml
Labels: kind/chore

#740 build(deps): bump policy-evaluator version to v0.16.2
  Cargo.lock
  Cargo.toml
  src/bench.rs
  src/run.rs
Labels: area/dependencies

#741 chore: bumps version in Cargo.toml to v1.11.0-rc3.
  Cargo.lock
  Cargo.toml
Labels: kind/chore

#745 chore: use tarpaulin-install action to install tarpaulin.
  .github/workflows/ci.yml
Labels: kind/chore

#746 fix(ci): set prerelease and latest flag properly.
  .github/workflows/release.yml
Labels: kind/bug

#748 chore: bump v1.11.0-rc5.
  Cargo.lock
  Cargo.toml
Labels: kind/chore

#755 chore: bump v1.11.0 version.
  Cargo.lock
  Cargo.toml
Labels: kind/chore
