Repository kubewarden/kwctl, pull requests merged in 2025-04, with the labels that each got.

#1166 fix(ci): build on windows
  .github/workflows/build.yml
  .github/workflows/ci.yml
Labels: kind/bug

#1175 chore(deps): fix RUSTSEC-2025-002
  Cargo.lock
Labels: kind/bug, kind/chore, area/dependencies

#1184 chore: bump version to v1.24.0-rc3.
  Cargo.lock
  Cargo.toml
Labels: kind/chore

#1169 feat: Improve policy version handling and verification
  src/rm.rs
Labels: kind/feature
