Repository kubewarden/kwctl, pull requests merged in 2025-02, with the labels that each got.

#1070 build(deps): bump policy-evaluator to v0.19.10
  Cargo.lock
  Cargo.toml
Labels: kind/chore, area/dependencies

#1073 chore(deps): update sigstore
  Cargo.lock
  Cargo.toml
  src/main.rs
  src/verify.rs
Labels: kind/chore, area/dependencies

#1081 feat: OCI annotations
  .taplo.toml
  Cargo.lock
  Cargo.toml
  cli-docs.md
  src/cli.rs
  src/push.rs
  src/scaffold/manifest.rs
  tests/e2e.rs
Labels: kind/feature

#1095 chore(deps): update dependencies
  Cargo.lock
  Cargo.toml
Labels: kind/chore, area/dependencies

#1098 ci: Add job for `crate-ci/typos` and fix typos on cli docs
  .github/workflows/ci.yml
  Makefile
  README.md
  cli-docs.md
  src/backend.rs
  src/callback_handler/proxy.rs
  src/cli.rs
  src/scaffold/manifest.rs
  tests/e2e.rs
Labels: kind/bug, kind/chore
