Repository kubewarden/kwctl, pull requests merged in 2025-07, with the labels that each got.

#1252 feat(capabilities): update policy-evaluator to v0.27.0.
  Cargo.lock
  Cargo.toml
Labels: kind/feature

#1277 feat: Honour policy mode, mutation, custom rejection mesage
  Cargo.toml
  src/command/run.rs
  src/command/run/evaluator.rs
  src/config/policy_definition.rs
Labels: kind/feature

#1282 chore(deps): update policy-evaluator
  Cargo.lock
  Cargo.toml
Labels: kind/chore, area/dependencies

#1286 chore: update cargo-audit exceptions
  .cargo/audit.toml
Labels: kind/chore

#1289 Migrate mailing list mentions to CNCF
  Cargo.toml
Labels: kind/tech-debt
