Repository kubewarden/kwctl, pull requests merged in 2025-03, with the labels that each got.

#1103 fix: handle single lines terminated by carriage return
  src/push.rs
Labels: kind/bug

#1105 feat: add gh release to artifacthub scaffold
  Cargo.lock
  Cargo.toml
  cli-docs.md
  src/cli.rs
  src/main.rs
  src/scaffold/artifacthub.rs
Labels: kind/feature

#1116 feat: add spinner while pulling resources
  Cargo.lock
  Cargo.toml
  src/pull.rs
Labels: kind/feature

#1127 refactor!: Change `kwctl inspect` colored output
  Cargo.lock
  Cargo.toml
  src/inspect.rs
Labels: kind/breaking-change

#1142 feat: scaffold artifacthub runs without params
  cli-docs.md
  src/cli.rs
  src/main.rs
  src/utils.rs
  tests/data/artifacthub/metadata.yml
  tests/e2e.rs
Labels: kind/feature

#1153 fix(cli): correct quotation marks with normal qutations.
  cli-docs.md
  src/cli.rs
Labels: kind/bug
